<a href="https://colab.research.google.com/github/ashutoshpatel01/CodeAlpha_Basic-File-Manager/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Fundamentals**

In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


Introduction to Tensors
 ## creating tensors
  tensors are created using toorch.sensor

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item() # getting back as in instead as it was tensor

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim # dimension no of "[] braclets"

1

In [7]:
vector.shape # we have 2 8 1 elements

torch.Size([2])

In [8]:
#MATRIX
matrix = torch.tensor([[7,8],[8,9]])
matrix

tensor([[7, 8],
        [8, 9]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim


3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#Random Tensors


In [27]:
#cretae Random tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5705, 0.0961, 0.3908, 0.2342],
        [0.0954, 0.0090, 0.6333, 0.7957],
        [0.8167, 0.1871, 0.2680, 0.0369]])

In [28]:
random_tensor.ndim

2

In [32]:
#creating tensors with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,color channels are (RGB)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [35]:
random_tensor = torch.rand(2,3,4)
random_tensor


tensor([[[2.0154e-01, 9.3371e-01, 6.6025e-01, 7.3715e-01],
         [6.2625e-01, 4.7772e-01, 8.1737e-01, 9.0565e-01],
         [4.5272e-01, 3.8634e-01, 7.6471e-01, 8.1837e-05]],

        [[8.5571e-01, 1.4189e-02, 7.6063e-01, 4.7968e-01],
         [2.3004e-01, 5.9817e-01, 6.5641e-01, 3.5606e-03],
         [7.7048e-01, 3.4268e-01, 3.8922e-01, 5.0618e-01]]])

In [37]:
random_tensor[0:1,2:,0:]

tensor([[[4.5272e-01, 3.8634e-01, 7.6471e-01, 8.1837e-05]]])

In [36]:
random_tensor.ndim

3

#### Zeros and Ones

In [38]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
# creating ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype

torch.float32

In [42]:
random_tensor.dtype

torch.float32

### creating a range of tensors

In [46]:
one_to_ten  =torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
torch.arange(start = 9,end = 34,step = 2)

tensor([ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [47]:
#creating a alike Tensor only dimension not value
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [48]:
#float 32 tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [49]:
float_32_tensor.dtype

torch.float32

In [50]:
#float 64 tensors
float_64_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
#float 32 tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None, # datatypes
                               device=None, # on which it is runnig cpu , gpu etc
                               requires_grad= False)
float_32_tensor

In [51]:
float_16_tensor = float_64_tensor.type(torch.float16)
float_16_tensor # changing the datatypes

tensor([3., 6., 9.], dtype=torch.float16)

In [55]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [59]:
bool_tensor = torch.full(size= (2,2,3),fill_value= True, dtype= torch.bool)
bool_tensor

tensor([[[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]]])

In [61]:
(bool_tensor * float_32_tensor)

tensor([[[3., 6., 9.],
         [3., 6., 9.]],

        [[3., 6., 9.],
         [3., 6., 9.]]])

In [62]:
(bool_tensor * float_32_tensor).shape # shape is attribute

torch.Size([2, 2, 3])

In [63]:
(bool_tensor * float_32_tensor).dtype

torch.float32

In [64]:
bool_tensor.size() # size is method or function

torch.Size([2, 2, 3])

In [65]:
bool_tensor.device # device on which tensor is intialised
# we can change the device as per use

device(type='cpu')

##Operations
#### Addition , Substraction, Multiplication(element_wise), division, & Matix Multiplicatio

In [99]:
# Addition

tensor = torch.tensor([1,2,3,4,45,5])
tensor + 10

tensor([11, 12, 13, 14, 55, 15])

In [100]:
tensor

tensor([ 1,  2,  3,  4, 45,  5])

In [102]:
tensor *= 10 # torch.mul(tensor, 10)

In [103]:
tensor

tensor([ 100,  200,  300,  400, 4500,  500])

In [105]:
tensor /10

tensor([ 10,  20,  30,  40, 450,  50])

In [106]:
tensor

tensor([ 100,  200,  300,  400, 4500,  500])

In [107]:
tensor /= 10
tensor

RuntimeError: result type Float can't be cast to the desired output type Long

In [108]:
tensor = tensor.type(torch.float32) # Change the data type to float32
tensor /= 10  # Perform the in-place division
tensor

tensor([ 10.,  20.,  30.,  40., 450.,  50.])

In [109]:
tensor = tensor.type(torch.long)
tensor

tensor([ 10,  20,  30,  40, 450,  50])

In [111]:
tensor -= 10
tensor

tensor([-10,   0,  10,  20, 430,  30])

In summary, 10 is subtracted twice because you used the -= operator twice. Each time it's used, it modifies the tensor directly, leading to the cumulative effect of two subtractions

###Matrix multiplication

Two main ways
1. Element _ wise implementation
2. Matix multiplication (dot Product "." -> a.b)

In [114]:
# Element - wise
tensor = torch.tensor([2,3,4])
tensor * tensor

tensor([ 4,  9, 16])

In [115]:
#Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(29)

In matrix multiplication do remember the how matrix multiplication is done in maths with poper dimension rule and result dimension.
In pytorch "matmul( m1, m2)" for matrix multiplication ofm1,m1 also "mm(m1,m2)" aa mm is alias of matmul

###Transpose of Matrix

In [116]:
tensor_1 = torch.tensor([[3,4,5],
                         [1,5,8]])
tensor_1


tensor([[3, 4, 5],
        [1, 5, 8]])

In [126]:
tensor_2 = tensor_1.T
# switched the dimension by transpose as same as maths

tensor_3 = torch.matmul(tensor_1,tensor_2)


In [128]:
tensor_3

tensor([[50, 63],
        [63, 90]])