<a href="https://colab.research.google.com/github/ashutoshpatel01/CodeAlpha_Basic-File-Manager/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Fundamentals**

In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


Introduction to Tensors
 ## creating tensors
  tensors are created using toorch.sensor

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item() # getting back as in instead as it was tensor

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim # dimension no of "[] braclets"

1

In [7]:
vector.shape # we have 2 8 1 elements

torch.Size([2])

In [11]:
#MATRIX
matrix = torch.tensor([[7,8],[8,9]])
matrix

tensor([[7, 8],
        [8, 9]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim


3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])